/**
 * @file flavortext.h
 * @author JuNi4
 * @brief Flavortext generator
 * @version 0.1
 * @date 2025-10-21
 * 
 * @copyright Copyright (c) 2025
 * 
 */

/*
   There are 304 * 302 * 101 = 9,272,608 different flavortext messages in this programm.
   The messages are generated by using 3 lists:
    A - contains verbs and adjectivs,
    B - contains objects, things and a view people and last but not least
    C - contains additional flavouring, that further describes the combination of A and B.

   If you have size constrains, like on a microcontroller, consider removing the c list and triming the a and b list. That should cut down the size.
    
   Inspired by https://github.com/ZackFreedman/Singularitron/blob/master/SingularitronFirmware/flavortext.h (and also a view words were taken from there).
   
   Some other words are from LLMs. If you don't want anything that might have been generated by a LLM, define _FLAVORTEXT_NO_AI_ while compiling. This will not include the small amount of words, generated by LLMs. Anything LLM generated is marked with ai.
*/

#ifndef _FLAVORTEXT_H_
#define _FLAVORTEXT_H_

/**
 * @brief Generates some flavortext
 * 
 * @return `char*` The resulting flavortext string (must be freed)
 */
char* flavortext();

#endif