/**
 * @file flavortext.c
 * @author JuNi4
 * @brief Flavortext generator
 * @version 0.1
 * @date 2025-10-21
 * 
 * @copyright Copyright (c) 2025
 * 
 */

#include "flavortext.h"
#include <string.h>
#include <stdlib.h>
#include <time.h>

/*
   TODO: Prohibit innapropreate combinations... maybe...
   TODO: more comprehensive flavortext building system than picking 3 strings at random
*/

// ai
#ifndef _FLAVORTEXT_NO_AI_
const char* RIP = " (RIP)";
const char* MOSES = " like Moses";
#endif

static const char* a[] = {
    // "positiv" / constructiv words
    "Activating",
    "Reinacting",
    "Creating",
    "Enlargening",
    "Adding",
    "Multiplying",
    "Scaling",
    "Doing quaternion operations on",
    "Watching",
    "Defending",
    "Manipulating",
    "Placing",
    "Toggeling",
    "Building",
    "Compiling",
    "Roleplaying",
    "Fixing",
    "Manipulating",
    "Eating",
    "Obliterating",
    "Petting",
    "Growing",
    "Taking over",
    "Calling",
    "Planting",
    "Allocating",
    "Booting",
    "Aligning",
    "Instancing",
    "Snorting",
    "Microwaving",
    "Binding",
    "Revving",
    "Polishing",
    "Fabricating",
    "Pinging",
    "Refactoring",
    "Configuring",
    "Calibrating",
    "Wrangling",
    "Tweaking",
    "Hacking",
    "Loading",
    "Quantifying",
    "Assembling",
    "Distilling",
    "Baking",
    "Receiving",
    "Unlocking",
    "Pressurizing",
    "Making",
    "Engaging",
    "Decrypting",
    "Synthesizing",
    "Predicting",
    "Analyzing",
    "Dispensing",
    "Firing",
    "Inserting",
    "Encouraging",
    "Extruding",
    "Accessing",
    "Sharpening",
    "Enhancing",
    "Cranking",
    "Stacking",
    "Crafting",
    "Rendering",
    "Mounting",
    "Generating",
    "Implementing",
    "Downloading",
    "Constructing",
    "Wow! Amazing",
    "Moistening",
    "Customizing",
    "Compensating",
    "Buffering",
    "Transferring",
    "Inducting",
    "Emitting",
    "Unzipping",
    "Squirting",
    "Feeding",
    "Buying",
    "Sparking",
    "Implanting",
    "Triangulating",
    "Injecting",
    "Linking",
    "Brewing",
    "Processing",
    "Deploying",
    "Tuning",
    "Attaching",
    "Training",
    "Ignoring",
    "Tapping",
    "Reloading",
    "Simulating",
    "Fluffing",
    "Filling",
    "Sorting",
    "Updating",
    "Upgrading",
    "Priming",
    "Tracing",
    "Inflating",
    "Wangjangling",
    "Charging",
    "Cracking",
    "Dialing",
    "Pimping",
    "Collecting",
    "Approaching",
    "Approving",
    "Sampling",
    "Energizing",
    "Stuffing",
    "Asking",
    "Allowing",
    "Bloating",
    "Enchanting",
    "Pushing",
    "Pulling",
    "Fetching",
    "Crystalizing",
    "Writing",
    "Gaining",
    "Editing",
    
    // negativ / deconstructiv words
    "Dividing",
    "Debloating",
    "Denying",
    "Shrinking",
    "Removing",
    "Killing",
    "Ending",
    "Disableing",
    "Discombobulating",
    "Deallocating",
    "Trashing",
    "Unplugging",
    "Revoking",
    "Forgetting",
    "Discarding",
    "Dropping",
    "Holstering",
    "Shredding",
    "Jettisoning",
    "Dissolving",
    "Liquidating",
    "Releasing",
    "Collimating",
    "Ejecting",
    "Ditching",
    "Leaking",
    "Selling",
    "Banishing",
    "Dereferencing",
    "Sacrificing",
    "Desoldering",
    "Destructing",
    "Decompiling",
    "Blowing",
    "Disengaging",
    "Digesting",
    "Smashing",
    "Encrypting",
    "Crashing",
    "Locking",
    "Purging",
    "Regretting",
    "Rewinding",
    "Freeing",
    "Deleting",
    "Closing",
    "Retracting",
    "Collapsing",
    "Liquefying",
    "Derezzing",
    "Stowing",
    "Archiving",
    "Suspending",
    "Suppressing",
    "Cleaning",
    "Squashing",
    "Securing",
    "Withdrawing",
    "Dumping",
    "Obfuscating",
    "Breaking",
    "Scrubbing",
    "Abandoning",
    "Flattening",
    "Stashing",
    "Finishing",
    "Evacuating",
    "Scrambling",
    "Recycling",
    "Crushing",
    "Zipping",
    "Unloading",
    "Disconnecting",
    "Loosening",
    "Containing",
    "Debating",
    "Detaching",
    "Neutralizing",
    "Salvaging",
    "Emptying",
    "Hiding",
    "Disarming",
    "Pickling",
    "Disregarding",
    "Yeeting",
    "Scrapping",
    "Deflating",
    "Discharging",
    "Deactivating",
    "Sterilizing",
    "Relieving",
    "Nuking",
    "Degaussing",
    "Dismissing",
    "Draining",
    "Rejecting",
    "Nerfing",
    "Paying",
    "Returning",
    "Unsticking",
    "Splitting",
    "Cancelling",
    "Shaming",
    "Embezzling",
    "Flinging",
    "Halting",
    "Arresting",
    "Burying",
    "Lying about",
    "Wasting",
    "rm -rf",
    "Blasting",
    
    // other
    "Made with",
    "Made from",
    "Reading",
    "Painting",
    "Dragging",
    "Including",
    "Raytracing",
    "Raymarching",
    "Pathtraycing",
    "Rasterizing",
    "I am",
    "Error:",
    "Folding",
    "Explodificating",
    "Stupififacting",
    "Your computer is being taken over by",
    "Strapping in",
    "Listening to",
    "Listing",
    "Ghosting",
    "Coding",
    "Rotting",
    "Toasting",
    "Cooking",
    "360 No-Scoping",
    "Enlightening",
    "Like",
    "Not like",
    "Quoting",
    "Typing",
    "Hooking up",
    "Combining",
    "Launching",
    "Throwing",
    "Equipping",
    "Blowing up",
    "Exploring",
    "Doing",
    "Tying",
    "Losing",
    "Mixing",
    "Hiring",
    "Citing",
    "Crediting",
    "Scoping",
    "Jingeling",
    "Dangeling",
    "Racing",
    "Trading",
    "Mailing",
    "Meeting",
    "Failing",
    "Lifting",
    "Storing",
    "Chasing",
    "Shaking",
    "Nesting",
    "Better than",
    "Remodulating",
    // ai
    #ifndef _FLAVORTEXT_NO_AI_
    "System status:",
    #endif
};

static const char* b[] = {
    "discombulator",
    "a watch",
    "compiler",
    "programm",
    "math",
    "physics",
    "photons",
    "electrons",
    "plants",
    "spaghetti",
    "pasta",
    "sauce",
    "space",
    "RAM",
    "VRAM",
    "GPU",
    "CPU",
    "core count",
    "brains",
    "video",
    "file",
    "fun",
    "happyness",
    "discontent",
    "agony",
    "remnant",
    "train",
    "trains",
    "time",
    "robot",
    "robots",
    "world",
    "Mars",
    "Earth",
    "Venus",
    "Mercury",
    "Pluto",
    "Neptune",
    "Uranus",
    "Jupiter",
    "Saturn",
    "univers",
    "internet",
    "computer",
    "stdio",
    "c++",
    "c",
    "Java",
    "Minecraft",
    "this code",
    "help",
    "hope",
    "vector",
    "vectors",
    "black hole",
    "black holes",
    "hard drive",
    "hard drives",
    "root",
    "user",
    "lore",
    "content",
    "API",
    "warp drive",
    "data",
    "AI",
    "crystals",
    "fluxgate",
    "flux compensator",
    "loud noises",
    "wires",
    "bytecode",
    "the truth",
    "conspiracy theorys",
    "magic",
    "hot lava",
    "lave",
    "bits",
    "bytes",
    "sensors",
    "signal",
    "the planet",
    "password",
    "chips",
    "circuits",
    "privacy",
    "synergy",
    "widgets",
    "lova",
    "love",
    "packets",
    "reality",
    "lasers",
    "protocols",
    "protocol",
    "voltage",
    "register",
    "puns",
    "dogecoins",
    "kittens",
    "dogs",
    "magic smoke",
    "plot device",
    "the core",
    "dank memes",
    "subroutines",
    "radiation",
    "steam",
    "trousers",
    "alcohol",
    "alcoholic drinks",
    "software",
    "holograms",
    "magnets",
    "inductors",
    "registors",
    "capacitors",
    "viewers",
    "sausage",
    "drama",
    "the future",
    "the present",
    "the past",
    "5G implant",
    "monkeys",
    "fluids",
    "the impostor",
    "beats",
    "dopamine",
    "neural networks",
    "comments",
    "ports",
    "you. Yes you",
    "[REDACTED]",
    "hot tub",
    "paperwork",
    "the 1%",
    "the Matrix",
    "variables",
    "IP address",
    "a house",
    "OpenGL",
    "Vulkan",
    "librarys",
    "is a lie",
    "GLaDOS",
    "portal",
    "cake",
    "Wheatly",
    "Intelligence Dampening Sphere",
    "Chell",
    "Freddy",
    "Foxy",
    "Bonny",
    "Chica",
    "W. Afton",
    "nightmares",
    "the mimic",
    "the puppet",
    "protostar",
    "neutronstar",
    "star",
    "galaxy",
    "Linux",
    "Tux",
    "windows",
    "MS DOS",
    "Microsoft",
    "GNU",
    "GRUB",
    "gcc",
    "VS Code",
    "assembly",
    "assembler",
    "kernel",
    "Iron Man",
    "magic hands man",
    "veggimite",
    "marmite",
    "mine turtles",
    "apt",
    "sudo",
    "vim",
    "x11",
    "win32",
    "%appdata%",
    "science",
    "Appature Science",
    "Steve",
    "Alex",
    "system32",
    "GTA VI",
    "again",
    "Batman",
    "turret",
    "Mojang",
    "[INSERT NAME HERE]",
    "jokes",
    "dad jokes",
    "the Joker",
    "redstone",
    "books",
    "the dead",
    "T1000",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "Euler",
    "Newton",
    "Einstein",
    "Planck",
    "Gaussian",
    "Hawking",
    "404",
    "Segmentation fault: Core dumped",
    "a British person",
    "cryogenic supply",
    "stasis chamber",
    "Enrichment Center",
    "matter-energy converter",
    "nuclear power plant",
    "uranium",
    "plutonium",
    "shulker boxes",
    "the environment",
    "bundles",
    "TCG",
    "giraffs",
    "public static void main(String[] args) {}",
    "nuke",
    "continents",
    "the elder scroll",
    "CMOS",
    "BIOS",
    "UEFI",
    "CMOS battery",
    "nothingness",
    "Stanley",
    "the narrator",
    "nuclear waste",
    "quantum computers",
    "anatomy",
    "me",
    "debugger",
    "emojis",
    "cmake",
    "clang",
    "Apple",
    "Metal",
    "DirectX",
    "emulators",
    "Saul Goodman",
    "Walter White",
    "Jesse Pinkman",
    "that pink sheep",
    "backgrounds",
    "mathematics",
    "folders",
    "text",
    "soup",
    "spaghetti monster",
    "virus",
    "malicious code",
    "Windows XP",
    "Reddit",
    "AMD",
    "NVidia",
    "Agent 47",
    "mass",
    "supercritical phase changer",
    "Aerogel",
    "pizza",
    "music",
    "nanobots",
    "guest wifi",
    "synthwaves",
    "videogames",
    "./src/*",
    "makefile",
    "bash",
    "/etc/fstab",
    "/etc/hosts",
    "/*",
    "g++",
    "linked list",
    "javascript",
    "typescript",
    "the 80s",
    "the 90s",
    "nothing",
    "stockfish",
    "shield harmonics",
    "phase variants",
    "temporal alignement",
    // AI extras
    #ifndef _FLAVORTEXT_NO_AI_
    "interdimensional tech babble",
    "[??]",
    "chaotic soup",
    "absurdities",
    "bangers",
    #endif
};

static const char* c[] = {
    #ifndef _FLAVORTEXT_NO_AI_
    // mostly AI
    " from the void",
    " (it glows)",
    " entropy",
    " config",
    " drizzle",
    " (with fire)",
    " in advance",
    " (for scale)",
    " (HR said it's fine)",
    "... probably",
    "... sideways",
    "... softly",
    "... it's different now",
    "... for later",
    "... please do not disturb",
    "... now with vibes",
    "... not sorry",
    "... pancakes ready",
    "... for now",
    " (twice!)",
    " for tax purposes",
    " but emotionally",
    " underwater and on fire",
    " as mandated by HR",
    " using deprecated methods",
    " in reverse",
    " with extra recursion",
    " to assert dominance",
    "... slightly radioactive",
    ", as a feature, not a bug",
    " (inside the simulation)",
    " (via USB 0.5)",
    " while screaming",
    " under NDA",
    " but lovingly",
    ", in full compliance with chaos theory",
    " during lunch",
    " inside a sandboxed environment",
    " with zero stack integrity",
    " powered by leftover RAM",
    " before the memory leaks",
    " while ignoring warnings",
    " using 7 layers of abstraction",
    " until core dump complete",
    " while skipping sanity checks",
    " during a solar flare",
    " without touching system32",
    " across all logical threads",
    " between stack overflows",
    ", optimized for regret",
    " running in reverse recursion",
    " during a null pointer exception",
    #endif
    // not ai
    " in RAM",
    " in ROM",
    " not storing it",
    "... maybe?",
    "... just kidding",
    " but in space",
    " just for fun",
    " and making it better",
    " but broken",
    " and breaking it",
    " very quickly",
    " backwards",
    " in a box",
    " in a nutshell",
    " while trying to remain stable",
    "... amazing",
    " in the cloud",
    " but on steroids",
    " going in circles",
    " whilst singing",
    " on MS DOS",
    " originally three times but superiors said no",
    " except why",
    "... what are you doing with your life?",
    " like Bill Gates always wanted",
    " crazily",
    " with a backflip",
    " /* why? */",
    " /* TODO: fix this */",
    " /* HELP */",
    " at the stratosphere",
    "... Call an ambulance",
    " as a ghost",
    " were your last words",
    " in 42ms",
    ".... .. ",
    ".-.. --- .-.. ",
    ". But hey, that's just a theory",
    " here",
    " in a western movie",
    " over wifi",
    " over lan",
    " sailing the seven seas",
    " illegally",
    " (very legal)",
    " at home",
    "... I would never",
    "... but not really...",
    " (running on MS DOS)",
};

unsigned long seed = 0;


char* flavortext()
{
    // make sure the seed is correct
    if (seed == 0)
    {
        seed = time(0);
        srand(seed);
    }

    const char* wa = a[rand() % (sizeof(a) / sizeof(*a))];
    const char* wb = b[rand() % (sizeof(b) / sizeof(*b))];
    const char* wc = c[rand() % (sizeof(c) / sizeof(*c))];
    
    int doC = (rand() % 100) < 20;

    #ifndef _FLAVORTEXT_NO_AI_
    if (!strcmp(wa, "Yeeting") && !strcmp(wb, "user") && doC)
    {
        wc = RIP;
    }
    else if (!strcmp(wa, "Dividing") && doC)
    {
        wc = MOSES;
    }
    #endif

    // create the output string
    size_t out_size = sizeof(char) * (strlen(wa) + strlen(wb) + (doC? strlen(wc) : 0) + 5);
    char* out = (char*)malloc(out_size);
    memset(out, ' ', out_size);

    // byte index
    size_t bi = 0;

    // write first part
    memcpy(out, wa, strlen(wa));
    bi += strlen(wa) + 1;

    // second part
    memcpy(out + bi, wb, strlen(wb));
    bi += strlen(wb);

    // third part
    if (doC)
    {
        memcpy(out + bi, wc, strlen(wc));
        bi += strlen(wc);
    }

    // '...' at the end
    memcpy(out + bi, "...", 3);
    // null byte terminator
    out[bi + 3] = 0;

    return out;
}
